linuxdeepin/deepin-compressor

src/source/mainwindow.cpp

fix: 解压文件界面，注释图标无图片显示

---

src/source/mainwindow.cpp

修复tab键的键盘交互在部分界面存在问题
Bug: https://pms.uniontech.com/bug-view-143225.html
Log: 修复tab键的键盘交互在部分界面存在问题

fix: 修复tab键的键盘交互在部分界面存在问题

---

3rdparty/interface/archiveinterface/archiveinterface.h

fix: 修复已知问题

---

src/source/common/eventlogutils.cpp
src/source/common/eventlogutils.h
src/source/mainwindow.cpp

feat: 数据埋点

---

CMakeLists.txt
src/CMakeLists.txt

Log: use GNUInstallDirs in CmakeLists
相关： https://github.com/linuxdeepin/developer-center/issues/3167

chore: use GNUInstallDirs in CmakeLists

---

CMakeLists.txt
tests/test-prj-running.sh

fix: ut单元测试

---

.reuse/dep5
3rdparty/interface/CMakeLists.txt
3rdparty/interface/common.cpp
3rdparty/interface/common.h
3rdparty/interface/commonstruct.h
3rdparty/interface/datamanager.cpp
3rdparty/interface/datamanager.h
3rdparty/interface/kcoreaddons_export.h
3rdparty/interface/queries.cpp
3rdparty/interface/queries.h
3rdparty/libarchive/CMakeLists.txt
3rdparty/libarchive/libarchive/CMakeLists.txt
3rdparty/libarchive/libarchive/libarchiveplugin.cpp
3rdparty/libarchive/libarchive/libarchiveplugin.h
3rdparty/libarchive/readonlylibarchiveplugin/CMakeLists.txt
3rdparty/libarchive/readonlylibarchiveplugin/kerfuffle_libarchive_readonly.json.license
3rdparty/libarchive/readonlylibarchiveplugin/readonlylibarchiveplugin.cpp
3rdparty/libarchive/readonlylibarchiveplugin/readonlylibarchiveplugin.h
3rdparty/libarchive/readwritelibarchiveplugin/CMakeLists.txt
3rdparty/libarchive/readwritelibarchiveplugin/kerfuffle_libarchive.json.license
3rdparty/libarchive/readwritelibarchiveplugin/readwritelibarchiveplugin.cpp
3rdparty/libarchive/readwritelibarchiveplugin/readwritelibarchiveplugin.h
3rdparty/libminizipplugin/CMakeLists.txt
3rdparty/libminizipplugin/kerfuffle_libminizip.json.license
3rdparty/libminizipplugin/libminizipplugin.cpp
3rdparty/libminizipplugin/libminizipplugin.h
LICENSES/GPL-2.0-or-later.txt
README.md
README.zh_CN.md

fix: 开源合规整改

---

src/source/mainwindow.cpp

解压到当前文件夹不创建文件夹
Bug: https://pms.uniontech.com/bug-view-162597.html
Log: 修复部分已知问题

fix: 修复解压到当前文件夹会创建文件夹问题

---

src/source/mainwindow.cpp

过滤特殊字符，使用最后一个文件夹名
Bug: https://pms.uniontech.com/bug-view-163153.html
Log: 修复部分已知问题

fix: 修复挂载目录压缩问题

---

src/source/mainwindow.cpp

添加文件删除事件处理
Bug: https://pms.uniontech.com/bug-view-164443.html
Log: 修复部分已知问题

fix: 修复文件打开后解压问题

---

3rdparty/libarchive/libarchive/libarchiveplugin.cpp
3rdparty/libzipplugin/libzipplugin.cpp
CMakeLists.txt
src/source/archivemanager/singlejob.cpp

修复超长文件双击打开失败的问题
Log: 修复超长文件双击打开失败的问题
/review 
@pengfeixx @myk1343 @wyu71

fix: 修复超长文件双击打开失败的问题

---

3rdparty/libminizipplugin/libminizipplugin.cpp
3rdparty/libzipplugin/libzipplugin.cpp

fix: 修复文件路径过长解压失败问题

---

src/source/page/compresssettingpage.cpp

tar.gz默认使用多线程解码
task: https://pms.uniontech.com/task-view-218697.html
Log: tar.gz默认使用多线程解码

feat: tar.gz默认使用多线程解码

---

src/assets/deepin-compressor/archive-manager/en_US/archive-manager.md
src/assets/deepin-compressor/archive-manager/zh_CN/archive-manager.md
src/assets/deepin-compressor/archive-manager/zh_HK/archive-manager.md
src/assets/deepin-compressor/archive-manager/zh_TW/archive-manager.md

去除帮助手册头注释
Bug: https://pms.uniontech.com/bug-view-173379.html
Log: 修复部分已知问题

fix: 修改帮助手册

---

.tx/deepin.conf
debian/changelog

fix: 添加changlog

---

.tx/deepin.conf
debian/changelog

v23 changelog
Log: v23 changelog

fix: v23 changelog

---

CMakeLists.txt
src/CMakeLists.txt

linglong start failed
Log: linglong start failed

fix: linglong start failed

---

src/source/dialog/openwithdialog/mimesappsmanager.cpp

修复V23无法打开压缩包中的文件
Bug: https://pms.uniontech.com/bug-view-189129.html
Log: 修复V23无法打开压缩包中的文件

fix: 修复V23无法打开压缩包中的文件

---

src/source/page/compresssettingpage.cpp

修复控制中心-个性化-字号20设置后压缩页面显示问题
Bug: https://pms.uniontech.com/bug-view-157289.html
Log: 修复控制中心-个性化-字号20设置后压缩页面显示问题

fix: 修复控制中心-个性化-字号20设置后压缩页面显示问题

---

src/source/mainwindow.cpp
src/source/page/compresssettingpage.cpp
src/source/page/progresspage.cpp
src/source/page/progresspage.h
src/source/tree/treeheaderview.cpp
src/source/tree/treeheaderview.h

合并release/eagle的修改到master
Log: 合并release/eagle的修改到master

chore: Merge branch 'release/eagle'

---

debian/changelog

changelog 5.12.15
Log: changelog 5.12.15

fix: changelog 5.12.15

---

3rdparty/libzipplugin/libzipplugin.cpp

适配window zip path
Log: 适配window zip path

fix: 适配window zip path

---

3rdparty/cli7zplugin/cli7zplugin.cpp
3rdparty/clizipplugin/cliplugin.cpp
3rdparty/interface/CMakeLists.txt
3rdparty/interface/archiveinterface/cliinterface.cpp
3rdparty/interface/archiveinterface/cliinterface.h
3rdparty/interface/archiveinterface/cliproperties.cpp
3rdparty/interface/common.cpp
3rdparty/interface/common.h
3rdparty/libarchive/libarchive/libarchiveplugin.cpp
3rdparty/libarchive/libarchive/libarchiveplugin.h
3rdparty/libarchive/readwritelibarchiveplugin/readwritelibarchiveplugin.cpp
3rdparty/libpigzplugin/libpigzplugin.cpp
3rdparty/libzipplugin/libzipplugin.cpp
3rdparty/libzipplugin/libzipplugin.h
debian/control
src/source/mainwindow.cpp
tests/UnitTest/3rdparty/cli7zplugin/CMakeLists.txt
tests/UnitTest/3rdparty/interface/CMakeLists.txt

长文件解压与带软连接压缩解压
Log: 长文件解压与带软连接压缩解压

fix: 长文件解压与带软连接压缩解压

---

debian/changelog

changelog 5.12.16
Log: changelog 5.12.16

fix: changelog 5.12.16

---

debian/changelog

changelog 5.12.17
Log: changelog 5.12.17

fix: changelog 5.12.17

---

src/source/tree/compressview.cpp
src/source/tree/uncompressview.cpp

修复v23 右键菜单中打开方式中LibreOffice Writer显示不全
Bug: https://pms.uniontech.com/bug-view-206221.html 修复v23 右键菜单中打开方式中LibreOffice Writer显示不全

fix: 修复v23 右键菜单中打开方式中LibreOffice Writer显示不全

---

debian/changelog

Description: 更新changelog(5.12.18)
Log: 更新changelog(5.12.18)

chore: 更新changelog(5.12.18)

---

3rdparty/interface/queries.cpp
src/source/dialog/popupdialog.cpp
src/source/dialog/settingdialog.cpp
src/source/mainwindow.cpp
src/source/page/compresspage.cpp
src/source/page/compresssettingpage.cpp
src/source/page/failurepage.cpp
src/source/page/progresspage.cpp
src/source/page/successpage.cpp
src/source/tree/datamodel.cpp
src/source/tree/datatreeview.cpp
src/source/tree/treeheaderview.cpp
src/source/tree/treeheaderview.h

fix: 适配紧凑模式

---

debian/changelog

changelog 5.12.19
Log: changelog 5.12.19

fix: changelog 5.12.19

---

debian/changelog

changelog 5.12.20
Log: changelog 5.12.20

fix: changelog 5.12.20

---

3rdparty/interface/archiveinterface/cliinterface.cpp

修复解压加密之后的rar压缩文件问题
Bug: https://pms.uniontech.com/bug-view-232911.html
Log: 修复解压加密之后的rar压缩文件问题

fix: 修复解压加密之后的rar压缩文件问题

---

3rdparty/interface/archiveinterface/cliinterface.cpp

Optimize annotations
Log: Optimize annotations

fix: Optimize annotations

---

debian/changelog

changelog 5.12.21
Log: changelog 5.12.21

fix: changelog 5.12.21

---

debian/changelog

changelog 5.12.22
Log: changelog 5.12.22

fix: changelog 5.12.22

---

src/source/mainwindow.cpp
src/source/page/compresssettingpage.cpp

dconfig 适配右键压缩
Bug: https://pms.uniontech.com/bug-view-239595.html
Log: dconfig 适配右键压缩zip 7z

fix: dconfig 适配右键压缩

---

debian/changelog

fix: tag 5.12.23

---

src/source/common/ddesktopservicesthread.h
src/source/common/pluginmanager.cpp

fix: build error on V23

---

3rdparty/libpigzplugin/libpigzplugin.cpp
3rdparty/libpigzplugin/libpigzplugin.h

tar.gz存储方式多线程压缩优化与进度显示
Bug: https://pms.uniontech.com/bug-view-241671.html
https://pms.uniontech.com/bug-view-241673.html
Log: tar.gz存储方式多线程压缩优化与进度显示

fix: tar.gz存储方式多线程压缩优化与进度显示

---

src/main.cpp
src/source/archivemanager/archivemanager.cpp
src/source/common/dbusadpator.cpp
src/source/common/dbusadpator.h
src/source/common/eventlogutils.cpp
src/source/common/eventlogutils.h
src/source/common/uistruct.h
src/source/mainwindow.cpp
src/source/page/uncompresspage.cpp
src/source/page/uncompresspage.h
src/source/tree/datatreeview.cpp
src/source/tree/datatreeview.h
src/source/tree/uncompressview.cpp

Merge into WPS custom code
Log: Merge into WPS custom code

fix: Merge into WPS custom code

---

debian/changelog

changelog 5.12.24
Log: changelog 5.12.24

fix: changelog 5.12.24

---

debian/changelog

changelog 5.12.25
Log: changelog 5.12.25

fix: changelog 5.12.25

---

3rdparty/interface/archiveinterface/cliinterface.cpp
3rdparty/interface/archiveinterface/cliinterface.h
3rdparty/interface/archiveinterface/cliproperties.cpp

Optimization of file list encryption method for decompression 
Task: https://pms.uniontech.com/task-view-326497.html 
Log: Optimization of file list encryption method for decompression

fix: Optimization of file list encryption method for decompression

---

debian/changelog

Update version to 5.12.26
相关PR:
* #171
Log: Update version to 5.12.26

chore: Update version to 5.12.26

---

3rdparty/libarchive/readwritelibarchiveplugin/kerfuffle_libarchive.json
CMakeLists.txt

屏蔽tar.zst格式
Bug: https://pms.uniontech.com/bug-view-222403.html
Log: 屏蔽tar.zst格式

fix: 屏蔽tar.zst格式

---

debian/changelog

update version to 6.0.1
Log: update version to 6.0.1
Bug: no

feat: update version to 6.0.1

---

3rdparty/interface/archiveinterface/cliinterface.cpp

修复7z加密压缩文件解压异常问题
Bug: https://pms.uniontech.com/bug-view-252509.html
Log: 修复7z加密压缩文件解压异常问题

fix: 修复7z加密压缩文件解压异常问题

---

debian/changelog

v23 Update tag to 6.0.2
Log: v23 Update tag to 6.0.2

fix: v23 Update tag to 6.0.2

---

3rdparty/libzipplugin/libzipplugin.cpp

Zip Path Traversal
Bug: https://pms.uniontech.com/bug-view-232873.html
Log: Zip Path Traversal

fix: Zip Path Traversal

---

src/source/common/ddesktopservicesthread.cpp
src/source/common/ddesktopservicesthread.h

Fix cimpile error: namespace error
Log: fix compile error

fix: compile error

---

src/source/page/compresssettingpage.cpp
src/source/page/compresssettingpage.h

dconfig tar.gz thread config optimization
Bug: https://pms.uniontech.com/bug-view-273093.html
Log: dconfig tar.gz thread config optimization

fix: dconfig tar.gz thread config optimization

---

src/source/mainwindow.cpp
src/source/page/compresssettingpage.cpp
src/source/page/compresssettingpage.h

fleming定制默认存储压缩方式优先
Log: fleming定制默认存储压缩方式优先

fix: fleming定制默认存储压缩方式优先

---

3rdparty/interface/queries.cpp
src/source/dialog/popupdialog.cpp
src/source/dialog/settingdialog.cpp
src/source/mainwindow.cpp
src/source/page/compresspage.cpp
src/source/page/compresssettingpage.cpp
src/source/page/failurepage.cpp
src/source/page/progresspage.cpp
src/source/page/successpage.cpp
src/source/tree/datamodel.cpp
src/source/tree/datamodel.h
src/source/tree/datatreeview.cpp
src/source/tree/treeheaderview.cpp
src/source/tree/treeheaderview.h

adapt compact mode
Log: adapt compact mode
Bug: https://pms.uniontech.com/bug-view-279797.html

fix: adapt compact mode

---

.reuse/dep5
LICENSES/LicenseRef-freeware
acknow.txt
debian/copyright

As title.
Log: Update license.
Task: https://pms.uniontech.com/story-view-37681.html

chore: update license

---

debian/changelog
linglong.yaml

Bump version to 6.0.5
Log: Bump version to 6.0.5

chore: Bump version to 6.0.5

---

debian/control
src/source/tree/datatreeview.cpp

Remove the virtual package libdisomaster-dev and fix build with Qt5.
Log: Fix CI build issue.

fix: [build]Fix CI build issue

---

src/source/mainwindow.cpp

优化默认压缩7z效率
Bug: https://pms.uniontech.com/bug-view-287203.html
Log: 优化默认压缩7z效率

fix: 优化默认压缩7z效率

---

README.md
README.zh_CN.md
debian/control
linglong.yaml

As title.
Log: Remove useless depends

chore: remove useless libdisomaster-dev

---

src/configs/json/org_deepin_compressor_method.hpp

add dfmvault support and optimize file handling
Log: add dfmvault support and optimize file handling

chore: add dfmvault support and optimize file handling

---

debian/changelog

v6.5.1 release after support Qt6.
Log: v6.5.1 release.

chore: [tag] New tag v6.5.1

---

debian/changelog

Bump version to 6.0.6
Log: Bump version to 6.0.6

chore: Bump version to 6.0.6

---

src/configs/json/org_deepin_compressor_method.hpp

add dfmvault support and optimize file handling
Log: add dfmvault support and optimize file handling

chore: add dfmvault support and optimize file handling (#259)

---

src/source/page/compresssettingpage.cpp

First enable input chinese character as password and alart for zip volume encryption.
Log: Fix encryption with chinese characters issue.
Bug: https://pms.uniontech.com/bug-view-305257.html

fix: Fix encryption with chinese characters issue

---

3rdparty/interface/archiveinterface/cliinterface.cpp
3rdparty/interface/common.cpp
3rdparty/interface/common.h
3rdparty/interface/commonstruct.h
3rdparty/libarchive/libarchive/libarchiveplugin.cpp
3rdparty/libzipplugin/libzipplugin.cpp
src/source/common/uistruct.h
src/source/mainwindow.cpp
translations/deepin-compressor_zh_CN.ts
translations/deepin-compressor_zh_HK.ts
translations/deepin-compressor_zh_TW.ts

Compressed file seek detection
Bug: https://pms.uniontech.com/bug-view-278613.html
Log: Compressed file seek detection

fix: Compressed file seek detection
