src/source/page/compresssettingpage.cpp
当滚动区域内的Widget高度发生变化时，页面刷新出现闪动，设置滚动区域内的Widget的最小高度为所有空间全展示的高度
Log: 103712 【KLUA】【专业版1050】【wayland】【归档管理器】部分104X、1050系统上点击“高级选项”按钮后出现窗口闪屏【1/10】
Bug: https://pms.uniontech.com/bug-view-103712.html
=> fix: 部分104X、1050系统上点击“高级选项”按钮后出现窗口闪屏

src/source/page/compresssettingpage.cpp, src/source/page/compresssettingpage.h
点击SwitchButton后，先修改ScrollArea内部的Widget高度
Log: 103712 【KLUA】【专业版1050】【wayland】【归档管理器】部分104X、1050系统上点击“高级选项”按钮后出现窗口
闪屏【1/10】
Bug: https://pms.uniontech.com/bug-view-103712.html
=> fix: 部分104X、1050系统上点击“高级选项”按钮后出现窗口闪屏，修改后出现收缩状态下也有滚动条显示的问题

CMakeLists.txt
Let's extend LDFLAGS instead of overriding it.
Log: Don't override LDFLAGS
=> fix: Don't override LDFLAGS

src/source/mainwindow.cpp
fix don't show progress dialog on first extract
Log: fix don't show progress dialog on first extract
=> fix: don't show progress dialog on first extract

src/source/dialog/popupdialog.cpp, src/source/dialog/popupdialog.h, src/source/tree/compressview.cpp
解压场景-重命名弹窗输入为空时，检查窗口显示,设置确认按钮置灰
Bug: https://pms.uniontech.com/bug-view-153129.html
Log: 解压场景-重命名弹窗输入为空时，检查窗口显示,设置确认按钮置灰
=> fix: bug 153129 解压场景-重命名弹窗输入为空时，检查窗口显示,设置确认按钮置灰

src/source/mainwindow.cpp
修复大压缩文件二次提取相同文件奔溃问题
Bug: https://pms.uniontech.com/bug-view-136823.html
Log: 修复大压缩文件二次提取相同文件奔溃问题
=> fix: 修复大压缩文件二次提取相同文件奔溃问题

src/source/mainwindow.cpp
外接扩展屏时，无权限的文件夹进行压缩操作，提示框显示在主屏正中间
Bug: https://pms.uniontech.com/bug-view-184223.html
Log: 外接扩展屏时，无权限的文件夹进行压缩操作，提示框显示在主屏正中间
=> fix: 外接扩展屏时，无权限的文件夹进行压缩操作，提示框显示在主屏正中间

src/source/tree/treeheaderview.cpp, src/source/tree/treeheaderview.h
修复焦点在返回按钮时，移入鼠标在移出鼠标时返回键无UI效果
Bug: https://pms.uniontech.com/bug-view-122587.html
Log: 修复焦点在返回按钮时，移入鼠标在移出鼠标时返回键无UI效果
=> fix: 修复焦点在返回按钮时，移入鼠标在移出鼠标时返回键无UI效果

src/source/mainwindow.cpp, src/source/page/progresspage.cpp, src/source/page/progresspage.h
修复tar.gz多线程（2-4-8线程）压缩暂停后，点击退出按钮再点击取消后压缩进度继续进行
Bug: https://pms.uniontech.com/bug-view-121145.html
Log: 修复tar.gz多线程（2-4-8线程）压缩暂停后，点击退出按钮再点击取消后压缩进度继续进行
=> fix: 修复tar.gz多线程（2-4-8线程）压缩暂停后，点击退出按钮再点击取消后压缩进度继续进行

3rdparty/libarchive/libarchive/libarchiveplugin.cpp
修复tar.xz压缩包中列表目录不以'/'结束而导致显示错误
Log: 修复tar.xz压缩包中列表目录不以'/'结束而导致显示错误
=> fix: 修复tar.xz压缩包中列表目录不以'/'结束而导致显示错误

src/source/tree/datamodel.cpp
Fixes the following build failures:
```
/home/felix/projects/deepin/deepin-compressor/src/source/tree/datamodel.cpp: In member function ‘virtual QVariant DataModel::data(const QModelIndex&, int) const’:
/home/felix/projects/deepin/deepin-compressor/src/source/tree/datamodel.cpp:105:17: error: ‘DGuiApplicationHelper’ has not been declared
105 |             if (DGuiApplicationHelper::instance()->sizeMode() == DGuiApplicationHelper::NormalMode) {
|                 ^~~~~~~~~~~~~~~~~~~~~
/home/felix/projects/deepin/deepin-compressor/src/source/tree/datamodel.cpp:105:66: error: ‘DGuiApplicationHelper’ has not been declared
105 |             if (DGuiApplicationHelper::instance()->sizeMode() == DGuiApplicationHelper::NormalMode) {
| …
```
=> fix: build failures for new dtkgui

3rdparty/libarchive/readwritelibarchiveplugin/readwritelibarchiveplugin.cpp, 3rdparty/libarchive/readwritelibarchiveplugin/readwritelibarchiveplugin.h
修改了3rdparty/libarchive的压缩逻辑,当在mtp中进行压缩时,首先在tmp下建立临时文件,然后再copy到对应目录
Log: 修改了3rdparty/libarchive的压缩逻辑,当在mtp中进行压缩时,首先在tmp下建立临时文件,然后再copy到对应目录
Bug: https://pms.uniontech.com/bug-view-237575.html
=> fix: 手机mtp模式挂载时,点击压缩无法正确压缩文件

3rdparty/interface/archiveinterface/cliinterface.cpp, 3rdparty/interface/archiveinterface/cliinterface.h, 3rdparty/interface/common.cpp, 3rdparty/interface/common.h, 3rdparty/libarchive/readwritelibarchiveplugin/readwritelibarchiveplugin.cpp
mtp内部重命名失败,建立临时文件copy过去
Log: mtp内部重命名失败,建立临时文件copy过去
Bug: https://pms.uniontech.com/bug-view-200113.html
=> fix: 手机MTP内部，拖拽文件到压缩文件图标上，压缩完成后，压缩文件变为tmp后缀文件

src/CMakeLists.txt, src/assets/org.deepin.compressor.method.json, src/source/page/compresssettingpage.cpp, src/source/page/compresssettingpage.h
dconfig 定制适配开发
Log: dconfig 定制适配开发
=> fix: dconfig 定制适配开发

3rdparty/interface/archiveinterface/cliinterface.cpp
修复小米手机mtp挂载拖拽文件到zip压缩文件添加失败问题
Bug: https://pms.uniontech.com/bug-view-200113.html
Log: 修复小米手机mtp挂载拖拽文件到zip压缩文件添加失败问题
=> fix: 修复小米手机mtp挂载拖拽文件到zip压缩文件添加失败问题

src/source/dialog/settingdialog.cpp
修复wps定制回合时，设置中‘解压后删除压缩文件’下拉选择框未置灰
Bug: https://pms.uniontech.com/bug-view-243643.html
Log: 修复wps定制回合时，设置中‘解压后删除压缩文件’下拉选择框未置灰
=> fix: 修复wps定制回合时，设置中‘解压后删除压缩文件’下拉选择框未置灰

src/source/page/compresssettingpage.cpp
修复点击压缩，在格式下拉列表中没有7z格式压缩的选项
Bug: https://pms.uniontech.com/bug-view-246539.html
Log: 修复点击压缩，在格式下拉列表中没有7z格式压缩的选项
=> fix: 修复点击压缩，在格式下拉列表中没有7z格式压缩的选项

debian/changelog
changelog 6.0.3
Log: changelog 6.0.3
=> fix: changelog 6.0.3

src/source/common/uitools.cpp
修复长文件名开启后，无法将文件拖到归档管理器应用中
Bug: https://pms.uniontech.com/bug-view-262097.html
Log: 修复长文件名开启后，无法将文件拖到归档管理器应用中
=> fix: 修复长文件名开启后，无法将文件拖到归档管理器应用中

3rdparty/libarchive/readwritelibarchiveplugin/kerfuffle_libarchive.json
与主线保持一致屏蔽tar.zst格式
Bug: https://pms.uniontech.com/bug-view-266021.html
Log: 与主线保持一致屏蔽tar.zst格式
=> fix: 与主线保持一致屏蔽tar.zst格式

src/source/page/compresssettingpage.cpp
change the default compressLevel to store
Log: change the default compressLevel
Bug: https://pms.uniontech.com/bug-view-270031.html
=> fix: change the default compressLevel

3rdparty/interface/archiveinterface/cliinterface.cpp
修复追加文件为软连接问题
Bug: https://pms.uniontech.com/bug-view-273297.html
Log: 修复追加文件为软连接问题
=> fix: 修复追加文件为软连接问题

3rdparty/libpigzplugin/libpigzplugin.cpp, 3rdparty/libpigzplugin/libpigzplugin.h
Fix pigz special character problem
Log: Fix pigz special character problem
Bug: https://pms.uniontech.com/bug-view-274761.html
=> fix: Fix pigz special character problem

3rdparty/libsinglefileplugin/singlefile/singlefileplugin.cpp
修复bzip2/xz/gzip/lzma压缩的单文件打开时文件时间显示问题
Bug: https://pms.uniontech.com/bug-view-275771.html
Log: 修复bzip2/xz/gzip/lzma压缩的单文件打开时文件时间显示问题
=> fix: 修复bzip2/xz/gzip/lzma压缩的单文件打开时文件时间显示问题

src/main.cpp
压缩本地快捷方式指向网络路径时，本地文件不允许拖拽到压缩快捷方式追加文件
Bug: https://pms.uniontech.com/bug-view-276309.html
Log: 压缩本地快捷方式指向网络路径时，本地文件不允许拖拽到压缩快捷方式追加文件
=> fix: 压缩本地快捷方式指向网络路径时，本地文件不允许拖拽到压缩快捷方式追加文件

3rdparty/libzipplugin/libzipplugin.cpp
修复zip加密压缩包输入错误密码后应提示密码错误，解压失败
Bug: https://pms.uniontech.com/bug-view-301765.html
Log: 修复zip加密压缩包输入错误密码后应提示密码错误，解压失败
=> fix: 修复zip加密压缩包输入错误密码后应提示密码错误，解压失败
